apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo-charlie
spec:
  standby:
    enabled: true
  # host: LoadBalancer-dc-bravo
  # change service type to loadbalancer  
  service: 
    type: LoadBalancer
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.6-0
  postgresVersion: 14
  # primary and replica TLS certs
  customTLSSecret:
    name: prim-hippo.tls
  customReplicationTLSSecret:
    name: rep-hippo.tls
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  #monitoring:
    #pgmonitor:
      #exporter:
        #image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.2.1-0
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-0
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
